services:
  studio-dev-be:
    platform: linux/amd64
    build:
      context: .
      dockerfile: studio/config/docker/Dockerfile.dev
    image: 637423646530.dkr.ecr.ap-northeast-1.amazonaws.com/optinist-cloud:latest
    working_dir: /app
    volumes:
      - .:/app
      # optinist data outputs directories
      - ../optinist-docker-volumes/.snakemake/:/app/.snakemake
      - ../optinist-docker-volumes/logs/:/app/logs
      - ../optinist-docker-volumes/studio_data/:/app/studio_data
    ports:
      - "0.0.0.0:8000:8000"
    command: poetry run python main.py --reload --host 0.0.0.0 --port 8000
    environment:
      PYTHONPATH: /app/
      TZ: Asia/Tokyo
      OPTINIST_DIR: /app/studio_data

  studio-dev-fe:
    image: node:20.8.0-alpine3.18
    working_dir: /app/frontend
    volumes:
      - ./frontend/:/app/frontend/:cached
    ports:
      - "0.0.0.0:3000:3000"
    command: ash -c 'yarn install && yarn start'
    environment:
      TZ: Asia/Tokyo
