version: "3.7"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
      - ./optinist:/optinist:cached
    ports:
      - 8000:8000
    environment:
      PYTHONPATH: .
      TZ: Asia/Tokyo
