version: "3"

services:
  studio-dev-be:
    build:
      context: .
      dockerfile: studio/config/docker/Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python main.py --reload --host 0.0.0.0 --port 8000
    environment:
      PYTHONPATH: /app/
      TZ: Asia/Tokyo

  studio-dev-fe:
    image: node:16.20.1-alpine
    working_dir: /app/frontend
    volumes:
      - ./frontend/:/app/frontend/
    ports:
      - "3000:3000"
    command: ash -c 'yarn install && yarn start'
