services:
  test_studio_backend:
    image: test_studio_backend
    container_name: test_studio_backend
    build:
      context: .
      dockerfile: studio/config/docker/Dockerfile.test
    environment:
      PYTHONPATH: .
      TZ: Asia/Tokyo
    command: bash -c "poetry run python3 -m pytest -s"
    volumes:
      - .:/app

  test_studio_frontend:
    image: test_studio_frontend
    container_name: test_studio_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    environment:
      TZ: Asia/Tokyo
    command: yarn test:ci
