version: "3"

services:
  studio:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    command: python main.py --host 0.0.0.0 --port 8000
    environment:
      PYTHONPATH: /app/
      TZ: Asia/Tokyo
