version: "3"

services:
  db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    env_file:
      - studio/config/.env
    volumes:
      - db_data:/var/lib/mysql

  studio:
    build:
      context: .
      dockerfile: studio/config/docker/Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    command: python main.py --host 0.0.0.0 --port 8000
    environment:
      PYTHONPATH: /app/
      TZ: Asia/Tokyo
    depends_on:
      - db

volumes:
  db_data:
