[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "optinist"
description = "Calcium Imaging Pipeline Tool"
version = "0.4.0"
readme = "README.md"
requires-python = "==3.8.*"
license = {file = "LICENSE"}
authors = [
  {name = "OIST"},
]
classifiers=[
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: MacOS :: MacOS X",
]
dependencies = [
  "fastapi==0.68.*",
  "uvicorn==0.15.*",
  "numpy==1.23.*",
  "aiofiles",
  "tqdm",
  "pyyaml",
  "imageio",
  "tifffile",
  "python-multipart",
  "future",
  "pynwb==2.2.0",
  "psutil",
  "nbstripout",
  "snakemake==7.24.*",
  "jinja2==3.0.*",
]

[project.optional-dependencies]
doc = [
  "sphinx>=4.3.0,<4.6.0",
  "sphinxcontrib-apidoc",
  "sphinx_rtd_theme",
  "sphinx-prompt",
  "sphinx-pyproject",
  "sphinx-autodoc-typehints",
  "sphinx-copybutton==0.5.0",
  "sphinx-autobuild==2021.3.14",
  "myst-parser",
]

[project.urls]
Documentation = "https://optinist.readthedocs.io"
Repository = "https://github.com/oist/optinist"

[project.entry-points."console_scripts"]
run_optinist = "optinist.__main__:main"

[tool.setuptools]
include-package-data = true
zip-safe = false
py-modules = ["Snakefile"]

[tool.setuptools.packages.find]
exclude = ["optinist/tests*"]

[tool.setuptools.package-data]
"*" = [
  "frontend/build/*",
  "frontend/build/static/*",
  "frontend/build/static/css/*",
  "frontend/build/static/js/*",
  "frontend/build/static/media/*",
  "app_config/*.yaml",
  "config/*.yaml",
  "conda/*.yaml",
  "Snakefile",
]

[tool.isort]
profile = "black"
