rules:
  input_0:
    input:
    - 1/test.tif
    output: default/smk_exec_suite2p/input_0/data_endoscope.pkl
    nwbfile:
      session_description: optinist
      identifier: optinist
      experiment_description: None
      device:
        name: Microscope device
        description: Microscope Information
        manufacturer: Microscope Manufacture
      optical_channel:
        name: OpticalChannel
        description: optical channel
        emission_lambda: 500.0
      imaging_plane:
        name: ImagingPlane
        description: standard
        imaging_rate: 30.0
        excitation_lambda: 900.0
        indicator: GCaMP
        location: V1
      image_series:
        starting_time: 0
        starting_frame:
        - 0
        save_raw_image_to_nwb: false
      ophys:
        plane_segmentation:
          name: PlaneSegmentation
          description: ''
    params: {}
    return_arg: input_0
    type: image
    hdf5Path: null
    matPath: null
    path: null
  suite2p_file_convert_1234:
    input:
    - default/smk_exec_suite2p/input_0/data_endoscope.pkl
    return_arg:
      input_0: image
    params:
      batch_size: 500
      do_registration: 1
      force_sktiff: false
      nchannels: 1
      nplanes: 1
    output: default/smk_exec_suite2p/suite2p_file_convert_1234/suite2p_file_convert.pkl
    type: suite2p_file_convert
    nwbfile: null
    hdf5Path: null
    matPath: null
    path: suite2p/suite2p_file_convert
  suite2p_roi_1234:
    input:
    - default/smk_exec_suite2p/suite2p_file_convert_1234/suite2p_file_convert.pkl
    return_arg:
      ops: ops
    params:
      allow_overlap: false
      high_pass: 100
      inner_neuropil_radius: 2
      max_iterations: 20
      max_overlap: 0.75
      min_neuropil_pixels: 350
      nbinned: 5000
      neucoeff: 0.7
      preclassify: 0
      soma_crop: true
      sparse_mode: true
      spatial_hp_detect: 25
      spatial_scale: 0
      tau: 1
      threshold_scaling: 1
    output: default/smk_exec_suite2p/suite2p_roi_1234/suite2p_roi.pkl
    type: suite2p_roi
    nwbfile: null
    hdf5Path: null
    matPath: null
    path: suite2p/suite2p_roi
last_output:
- default/smk_exec_suite2p/suite2p_roi_1234/suite2p_roi.pkl
