
fr: 30                             # imaging rate in frames per second
decay_time: 0.4                    # length of a typical transient in seconds

# motion correction parameters
strides: [48, 48]          # start a new patch for pw-rigid motion correction every x pixels
overlaps: [24, 24]         # overlap between pathes (size of patch strides+overlaps)
max_shifts: [6,6]          # maximum allowed rigid shifts (in pixels)
max_deviation_rigid: 3     # maximum shifts deviation allowed for patch with respect to rigid shifts
pw_rigid: True             # flag for performing non-rigid motion correction

# parameters for source extraction and deconvolution
p: 1                       # order of the autoregressive system
nb: 2                     # number of global background components
merge_thr: 0.85            # merging threshold, max correlation allowed
rf: 15                     # half-size of the patches in pixels. e.g., if rf=25, patches are 50x50
stride: 6             # amount of overlap between the patches in pixels
K: 4                       # number of components per patch
gSig: [4, 4]               # expected half size of neurons in pixels
method_init: 'greedy_roi'  # initialization method (if analyzing dendritic data using 'sparse_nmf')
ssub: 1                    # spatial subsampling during initialization
tsub: 1                    # temporal subsampling during intialization

# parameters for component evaluation
min_SNR: 2.0               # signal to noise ratio for accepting a component
rval_thr: 0.85              # space correlation threshold for accepting a component
min_cnn_thr: 0.99              # threshold for CNN based classifier
cnn_lowest: 0.1 # neurons with cnn probability lower than this value are rejected

rolling_sum: True
only_init: True
use_cnn: True