version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(asctime)s %(levelname)s: %(funcName)s():%(lineno)d - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
  rotating_file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: default
    filename: logs/expdb/migration.log
    when: midnight
    interval: 1
    backupCount: 365
root:
  level: INFO
  handlers: [console, rotating_file]
