version: 1
disable_existing_loggers: true
formatters:
  default:
    (): "uvicorn.logging.DefaultFormatter"
    fmt: "%(asctime)s %(levelprefix)s %(message)s"
  access:
    (): "uvicorn.logging.AccessFormatter"
    fmt: "%(asctime)s %(levelprefix)s %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
  rotating_file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: default
    filename: studio/logs/app.log
    when: midnight
    interval: 1
    backupCount: 7
loggers:
  uvicorn:
    level: INFO
    handlers: [console]
root:
  level: INFO
  handlers: [rotating_file]
