"""add dataview feature

Revision ID: 4df5949c42ef
Revises: 86201451bfdd
Create Date: 2025-07-14 10:08:42.263790

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4df5949c42ef"
down_revision = "86201451bfdd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    columns_to_add = [
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column("thumbnails", sa.JSON(), nullable=True),
        sa.Column(
            "success", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "analyzed_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "publish_status",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="0: private, 1: public",
        ),
    ]

    # Execute add_column to experiment_records in bulk
    for column in columns_to_add:
        op.add_column("experiment_records", column)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    columns_to_drop = [
        "name",
        "thumbnails",
        "success",
        "analyzed_at",
        "publish_status",
    ]

    # Execute drop_column to experiment_records in bulk
    for column in columns_to_drop:
        op.drop_column("experiment_records", column)

    # ### end Alembic commands ###
