# on:
#   pull_request:
#     branches:
#       - develop
#     types: [closed]

name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    # if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: push
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          run: |
            cd frontend
            yarn build
            git add build
            git commit -m"build frontend"
            git push origin develop
