# on:
#   pull_request:
#     branches:
#       - develop
#     types: [closed]

name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    # if: github.event.pull_request.merged == true
    runs-on: self-hosted
#     env:
#       REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: push
        env:
          CI: false
        run: |
          cd frontend
          rm -rf node_modules
          yarn install
          yarn build
          git add build
          git commit -m"build frontend"
          git push origin develop
