# on:
#   pull_request:
#     branches:
#       - develop
#     types: [closed]

name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    # if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
    steps:
      - uses: actions/checkout@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
      - name: push
        run: |
          cd frontend
          yarn build
          git add build
          git commit -m"build frontend"
          git push origin develop
