on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: github/login-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        run: |
          cd frontend
          yarn build
          git add build
          git commit -m"build frontend"
          git push origin develop
