name: Codespell
on:
  pull_request:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: codespell-project/actions-codespell@v2
        with:
          args: "--skip='./dist,./frontend/node_modules,./logs'"
