on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          cd frontend
          yarn build
          git add build
          git commit -m"build frontend"
          git push origin develop