name: Tests

on:
  pull_request:
    branches:
      - main
      - develop-main
      - develop-feature
    paths-ignore:
      - "docs/**"

  workflow_dispatch:

# Test jobs are separated for parallel execution and clearer failure identification
jobs:
  # Backend and Lambda tests
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run backend tests
        shell: bash
        run: |
          make test_backend


  # Frontend tests
  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run frontend tests
        shell: bash
        run: |
          make test_frontend
