standard_x_mean: True
standard_x_std: True

standard_y_mean: True
standard_y_std: True

transpose_x: False
transpose_y: False

behavior: 'c'
add_constant: False
link: 'log'
family: 'Gaussian'

offset:
exposure:
missing:

target_index: 0